### ISSUE TITLE
"Triangulation and Plane Estimation" cell does not reset

### ISSUE THREAD

**Issue by loolirer** [debOliveira/MoCapRasp#3]
When ran more than once data gets scrambled. If you want it to run again you need to re-run the notebook debugOnline.ipynb from the beginning.

It's crucial for debugging to it correctly resets after re-running it!

**Comment by debOliveira** [comment]
@loolirer When running here at the lab-pc, there is no bug. Could you confirm the cell or if the problem was corrected?

**Comment by debOliveira** [comment]
Problem not found.
